#!/usr/bin/env bash
# List all my private repo urls
# Add this script to the path and call it in /home/git/.bash_profile of my bare git server

git_path=/srv/git
fd --base-directory=$git_path -uue git -x echo "git@git.labfall.com:$git_path/{}"

